name: Bitbake Core Image Sato
# works with
# act -r -P ubuntu-latest=-self-hosted --artifact-server-path $HOME/.act push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, "${{ github.actor }}"]
    #runs-on: [self-hosted, linux, x64]
    steps:
    - name: echo-default-env-veriables
      run: env

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Bitbake in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -v /home/archon/data:/home/jenkins/data \
          -e BB_ENV_PASSTHROUGH_ADDITIONS="DL_DIR SSTATE_DIR" \
          -e SSTATE_DIR=/home/jenkins/data/bitbake.sstate \
          -e DL_DIR=/home/jenkins/data/bitbake.downloads \
          -w /workspace \
          johnkday/tselb:1 \
          /bin/bash -c 'source oe-init-build-env && bitbake core-image-minimal'

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ${{ github.workspace }}/build/tmp/deploy/images/qemux86-64/
        compression-level: 0
