name: Bitbake Core Image Sato

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Bitbake in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          johnkday/tselb:1 \
          /bin/bash -c "source /workspace/poky/oe-init-build-env && bitbake core-image-sato"

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ${{ github.workspace }}/poky/build/tmp/deploy/images/qemux86-64
